### ISSUE TITLE
QR Orientation variable not available?

### ISSUE THREAD

**Issue by xuala69** [yushulx/flutter_barcode_sdk#1]
I've tested the example given for the package but the  BarcodeResult model doesn't have an Orientation variable as far as I can see. Is there a way to get the orientation from the other variables or the orientation is not available for flutter ?

**Comment by yushulx** [comment]
@xuala69 it's an ongoing project. Your required variable is supported by native barcode SDK, but not implemented in the Flutter plugin yet.

**Comment by yushulx** [comment]
@xuala69 I just added a barcode angle variable to the plugin. You can have a try.

**Comment by xuala69** [comment]
Excellent Thank you
