### ISSUE TITLE
Error installing DynamsoftBarcodeReader

### ISSUE THREAD

**Issue by ChatchaiBuekban** [yushulx/flutter_barcode_sdk#15]
-> Installing DynamsoftBarcodeReader (8.6.0)
     > Git download
     > Git download
         $ /usr/local/bin/git clone https://github.com/Dynamsoft/DynamsoftBarcodeReader.git /var/folders/v9/k9r61j1n7nzgm4vqlfqplqz40000gn/T/d20210831-13876-1mt6rl4 --template= --single-branch --depth 1 --branch
         8.6.0

    [!] Error installing DynamsoftBarcodeReader
    [!] /usr/local/bin/git clone https://github.com/Dynamsoft/DynamsoftBarcodeReader.git /var/folders/v9/k9r61j1n7nzgm4vqlfqplqz40000gn/T/d20210831-13876-1mt6rl4 --template= --single-branch --depth 1 --branch 8.6.0

**Comment by yushulx** [comment]
@ChatchaiBuekban the plugin only supports Dynamsoft Barcode Reader 8.2. Please specify the version number. Alternatively, you can download the repo to build with the framework [https://github.com/yushulx/flutter_barcode_sdk/tree/main/ios](https://github.com/yushulx/flutter_barcode_sdk/tree/main/ios).
