### ISSUE TITLE
build error with gradle 7.1:allowInsecureProtocol

### ISSUE THREAD

**Issue by nuzhata** [yushulx/flutter_barcode_sdk#17]
Your build.gradle must be changed like this:
rootProject.allprojects {
    repositories {
        maven {
            url "http://download2.dynamsoft.com/maven/dbr/aar"
            allowInsecureProtocol = true
        }
        google()
        jcenter()
    }
}

**Comment by yushulx** [comment]
@nuzhata it's fixed. Please check out the latest version. Thanks for your feedback.
