### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by xuala69** [yushulx/flutter_barcode_sdk#2]
As far as I can see, the sdk is paid for Native platforms and other hybrid platforms and is also hinted for Flutter to get a trial license. However, there is nothing written on how to apply the trial key(after getting one from the website) on flutter and how (if when) we may enter a license key upon purchase. I've gone through the documentations at dynamsoft.com but didn't find anything useful for Flutter. Would be great if you could update  the documentation explaining the above queries.

**Comment by yushulx** [comment]
@xuala69 I'll add it later. Thanks for your suggestion.

**Comment by yushulx** [comment]
@xuala69 I've updated the project. Please check out the license usage instruction.
![image](https://user-images.githubusercontent.com/2202306/117433483-193ac280-af5e-11eb-8c17-e5e6de3299b4.png)
