### ISSUE TITLE
android version won't compile without enabled flag

### ISSUE THREAD

**Issue by nohkumado** [yushulx/flutter_barcode_sdk#27]
Hello,
please add
flutter_barcode_scanner/example/android/app/src/main/AndroidManifest.xml+25

android:exported="true"
to be able to run it on sdk version 31
thanks

**Comment by yushulx** [comment]
@nohkumado thanks for your feedback. I've added the patch https://github.com/yushulx/flutter_barcode_sdk/commit/5acb09422c50aa29fe6d18d2af365484a53ea87d.

**Comment by yushulx** [comment]
@nohkumado [v2.0.1](https://pub.dev/packages/flutter_barcode_sdk) is online.
