### ISSUE TITLE
i was unable to build for ios

### ISSUE THREAD

**Issue by odejinmi** [yushulx/flutter_barcode_sdk#30]
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/user/StudioProjects/mcdflutter/ios/Pods/DynamsoftBarcodeReader/DynamsoftBarcodeReader.framework/DynamsoftBarcodeReader' for architecture arm64

**Comment by yushulx** [comment]
@odejinmi DynamsoftBarcodeReader.framework does not support simulator. Have you tried iPhone or iPad?

**Comment by odejinmi** [comment]
@yushulx i got this error when trying to archiving for device

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code


Error (Xcode): Undefined symbol: _OBJC_CLASS_$_iTextResult


Error (Xcode): Undefined symbol: _OBJC_CLASS_$_DynamsoftBarcodeReader


Encountered error while archiving for device.

**Comment by odejinmi** [comment]
@yushulx i'm having another issue wen releasing the macos version 

ld: warning: ignoring file /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_sdk-2.0.3/macos/lib/libDynamsoftBarcodeReader.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DynamsoftBarcodeReader", referenced from:
      objc-class-ref in FlutterBarcodeSdkPlugin.o
  "_OBJC_CLASS_$_iTextResult", referenced from:
      objc-class-ref in FlutterBarcodeSdkPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yushulx** [comment]
@odejinmi the `libDynamsoftBarcodeReader.dylib` only supports x86_64

**Comment by odejinmi** [comment]
> @odejinmi the `libDynamsoftBarcodeReader.dylib` only supports x86_64

Wot will I do to be able to build the project

**Comment by yushulx** [comment]
@odejinmi can you build it with x86_64 arch and run the app with rosetta?

**Comment by yushulx** [comment]
@odejinmi please try the attached `libDynamsoftBarcodeReader.dylib` file. 
[Mac_Arm64.zip](https://github.com/yushulx/flutter_barcode_sdk/files/9155559/Mac_Arm64.zip)

**Comment by odejinmi** [comment]
> @odejinmi can you build it with x86_64 arch and run the app with rosetta?

How do I do that
