### ISSUE TITLE
无法编译，flutter sdk 2.5.3

### ISSUE THREAD

**Issue by qinjinze** [yushulx/flutter_barcode_sdk#33]
D:\app\flutter_barcode_sdk-main\flutter_barcode_sdk-main\example>flutter run
Running "flutter pub get" in example...                            601ms
Launching lib\main.dart on 5G in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: �����Ԫ�� (uri:"", local:"base-extension")������Ԫ��Ϊ<{}codename>,<{}layoutlib>,<{}api-level>
Running Gradle task 'assembleDebug'...                              5.9s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                14.6s
W/FlutterActivityAndFragmentDelegate(19930): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Syncing files to device 5G...                                       74ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on 5G is available at: http://127.0.0.1:55729/S2RI9MOX0Ds=/
I/zygote64(19930): Rejecting re-init on previously-failed class java.lang.Class<com.dynamsoft.dbr.BarcodeReader$3>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dynamsoft/dce/DCEFrameListener;
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dynamsoft.dce.DCEFrameListener" on path: DexPathList[[zip file "/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base
.apk"],nativeLibraryDirectories=[/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/lib/arm64, /data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base.apk!/lib/arm64-v8a, /system/l
ib64, /vendor/lib64]]
I/zygote64(19930):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930):
I/zygote64(19930): Rejecting re-init on previously-failed class java.lang.Class<com.dynamsoft.dbr.BarcodeReader$3>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dynamsoft/dce/DCEFrameListener;
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dynamsoft.dce.DCEFrameListener" on path: DexPathList[[zip file "/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base
.apk"],nativeLibraryDirectories=[/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/lib/arm64, /data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base.apk!/lib/arm64-v8a, /system/l
ib64, /vendor/lib64]]
I/zygote64(19930):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930):
I/zygote64(19930): Rejecting re-init on previously-failed class java.lang.Class<com.dynamsoft.dbr.BarcodeReader$3>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dynamsoft/dce/DCEFrameListener;
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dynamsoft.dce.DCEFrameListener" on path: DexPathList[[zip file "/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base
.apk"],nativeLibraryDirectories=[/data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/lib/arm64, /data/app/com.dynamsoft.flutter_barcode_sdk_example-xQutQFmUmQCYsXYr3CwP7w==/base.apk!/lib/arm64-v8a, /system/l
ib64, /vendor/lib64]]
I/zygote64(19930):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19930):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19930):   at void com.dynamsoft.dbr.BarcodeReader.initLicense(java.lang.String, com.dynamsoft.dbr.DBRLicenseVerificationListener) (BarcodeReader.java:198)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.BarcodeManager.setLicense(java.lang.String, io.flutter.plugin.common.MethodChannel$Result) (BarcodeManager.java:102)
I/zygote64(19930):   at void com.dynamsoft.flutter_barcode_sdk.FlutterBarcodeSdkPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (FlutterBarcodeSdkPlugin.java:60)
I/zygote64(19930):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:233)
I/zygote64(19930):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, java.nio.ByteBuffer, int) (DartMessenger.java:84)
I/zygote64(19930):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, java.nio.ByteBuffer, int) (FlutterJNI.java:865)
I/zygote64(19930):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19930):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19930):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19930):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6548)
I/zygote64(19930):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19930):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(19930):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:866)
I/zygote64(19930):
I/zygote64(19930): The ClassLoaderContext is a special shared library.
D/NetworkSecurityConfig(19930): No Network Security Config specified, using platform default
Activating Dart DevTools...                                      1,589ms
D/libc-netbsd(19930): getaddrinfo: get result from proxy gai_error = 0
I/System.out(19930): port:443
I/System.out(19930): [OkHttp] sendRequest>>
I/System.out(19930): [OkHttp] sendRequest<<
E/AndroidRuntime(19930): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(19930): Process: com.dynamsoft.flutter_barcode_sdk_example, PID: 19930
E/AndroidRuntime(19930): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(19930):        at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime(19930):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(19930):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(19930):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(19930):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(19930):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(19930):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(19930):        at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(19930): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime(19930):        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1280)
E/AndroidRuntime(19930):        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:952)
E/AndroidRuntime(19930):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:169)
E/AndroidRuntime(19930):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(19930):        at com.dynamsoft.flutter_barcode_sdk.BarcodeManager$1.DBRLicenseVerificationCallback(BarcodeManager.java:107)
E/AndroidRuntime(19930):        at com.dynamsoft.dbr.BarcodeReader$DBRGetLicenseTaskEx.doInBackground(BarcodeReader.java:255)
E/AndroidRuntime(19930):        at com.dynamsoft.dbr.BarcodeReader$DBRGetLicenseTaskEx.doInBackground(BarcodeReader.java:235)
E/AndroidRuntime(19930):        at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(19930):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(19930):        ... 4 more
I/Process (19930): Sending signal. PID: 19930 SIG: 9
Lost connection to device.

D:\app\flutter_barcode_sdk-main\flutter_barcode_sdk-main\example>

**Comment by yushulx** [comment]
@qinjinze  I doubt you changed the version of Dynamsoft Android Barcode Reader SDK:

```groovy
dependencies {
    implementation 'com.dynamsoft:dynamsoftbarcodereader:9.0.0@aar'
}
```

Otherwise, you should not get the issue:

```bash
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dynamsoft/dce/DCEFrameListener;
```

The latest version of Dynamsoft Barcode Reader (Android and iOS) has a strong correlation with Dynamsoft Camera Enhancer (DCE), which is not compatible with current `flutter_barcode_sdk`. If you do want to use DCE, please install https://pub.dev/packages/dynamsoft_capture_vision_flutter
