### ISSUE TITLE
Attention(exceptionCode:-20200)

### ISSUE THREAD

**Issue by ThanatosDan** [yushulx/flutter_barcode_sdk#37]
flutter_barcode_sdk: ^2.2.2
PHONE:SMT733

I scan the barcode and get the following exception：
[Attention(exceptionCode:-20200)] P*40***22323001*

**Comment by yushulx** [comment]
You need to get a valid license from [https://www.dynamsoft.com/customer/license/trialLicense?product=dbr](https://www.dynamsoft.com/customer/license/trialLicense?product=dbr)
