### ISSUE TITLE
Dynamic libraries do not support arm64

### ISSUE THREAD

**Issue by sliderss** [yushulx/flutter_barcode_sdk#38]
ld: warning: ignoring file /Users/myself/Downloads/flutter_barcode_sdk-main/macos/lib/libDynamsoftBarcodeReader.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DynamsoftBarcodeReader", referenced from:
      objc-class-ref in FlutterBarcodeSdkPlugin.o
  "_OBJC_CLASS_$_iTextResult", referenced from:
      objc-class-ref in FlutterBarcodeSdkPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by sliderss** [comment]
arm64 will still give an error：
ld: warning: directory not found for option '-L/Users/myself/Downloads/flutter_barcode_sdk-main/example/macos/../../macos/libs'
dyld[86770]: Library not loaded: @loader_path/libDynamsoftBarcodeReader.dylib
  Referenced from: <B131EE14-78C6-39A8-839E-8F859A19431D> /Users/myself/Downloads/flutter_barcode_sdk-main/example/build/macos/Build/Products/Debug/flutter_barcode_sdk_example.app/Contents/MacOS/flutter_barcode_sdk_example
  Reason: tried: '/Users/myself/Downloads/flutter_barcode_sdk-main/example/build/macos/Build/Products/Debug/flutter_barcode_sdk_example.app/Contents/MacOS/libDynamsoftBarcodeReader.dylib' (no such file), '/usr/local/lib/libDynamsoftBarcodeReader.dylib' (no such file), '/usr/lib/libDynamsoftBarcodeReader.dylib' (no such file, not in dyld cache)
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on macOS.

**Comment by yushulx** [comment]
@sliderss currently, the mac dylib only supports x86_64

**Comment by yushulx** [comment]
@sliderss here are the arm64 dylibs
[Mac_Arm64.zip](https://github.com/yushulx/flutter_barcode_sdk/files/11560154/Mac_Arm64.zip)

**Comment by yushulx** [comment]
@sliderss  I apologize for the inconvenience, but according to the [package publishing policy](https://dart.dev/tools/pub/publishing), a package must be smaller than 100 MB after gzip compression. The use of universal dylib files would exceed this size limit for my package. Thank you for your understanding.

**Comment by sliderss** [comment]
@yushulx thank you.

**Comment by TamirlanBir** [comment]
what should we do with this zip file ?

**Comment by yushulx** [comment]
@TamirlanBir extract the dylib files from the zip file and overwrite the dylib files in https://github.com/yushulx/flutter_barcode_sdk/tree/main/macos/lib

**Comment by yushulx** [comment]
The latest v2.2.5 has replaced x86_64 libs with arm64 libs in macOS plugin.

**Comment by yushulx** [comment]
@TamirlanBir @sliderss Please try v2.2.5.
