### ISSUE TITLE
Execution failed for task ':flutter_barcode_sdk:generateReleaseRFile'.

### ISSUE THREAD

**Issue by han1548772930** [yushulx/flutter_barcode_sdk#41]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_barcode_sdk:generateReleaseRFile'.
> Could not resolve all files for configuration ':flutter_barcode_sdk:releaseCompileClasspath'.
   > Could not resolve com.dynamsoft:dynamsoftbarcodereader:9.6.20.
     Required by:
         project :flutter_barcode_sdk
      > Could not resolve com.dynamsoft:dynamsoftbarcodereader:9.6.20.
         > Could not get resource 'https://download2.dynamsoft.com/maven/aar/com/dynamsoft/dynamsoftbarcodereader/9.6.20/dynamsoftbarcodereader-9.6.20.pom'.
            > Could not GET 'https://download2.dynamsoft.com/maven/aar/com/dynamsoft/dynamsoftbarcodereader/9.6.20/dynamsoftbarcodereader-9.6.20.pom'.
               > Connection reset

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Running Gradle task 'assembleRelease'...                           19.9s
[!] Gradle threw an error while downloading artifacts from the network.
Retrying Gradle Build: #5, wait time: 1600ms

**Comment by han1548772930** [comment]
I downloaded DynamsoftBarcodeReader. aar, but where should I put it and how to reference it

**Comment by yushulx** [comment]
@han1548772930 I think your issue is caused by network connection. To use the local `*.aar` file, you can create a `libs` folder under [https://github.com/yushulx/flutter_barcode_sdk/tree/main/android](https://github.com/yushulx/flutter_barcode_sdk/tree/main/android) directory, and then copy your aar files into the folder. After that, configure the `build.gradle` file as follows:
 ```gradle
     repositories {
       flatDir {
           dirs 'libs'
       }
     }
     dependencies {
        implementation(name: 'name-of-your-aar-file', ext: 'aar')
     }
 ```

**Comment by han1548772930** [comment]
> @han1548772930我认为您的问题是由网络连接引起的。要使用本地`*.aar`文件，可以在https://github.com/yushulx/flutter_barcode_sdk/tree/main/android`libs`目录下创建一个文件夹，然后将 aar 文件复制到该文件夹​​中。之后，配置文件如下：[](https://github.com/yushulx/flutter_barcode_sdk/tree/main/android)`build.gradle`
> 
> ```groovy-gradle
>     repositories {
>       flatDir {
>           dirs 'libs'
>       }
>     }
>     dependencies {
>        implementation(name: 'name-of-your-aar-file', ext: 'aar')
>     }
> ```

thx
