### ISSUE TITLE
Error on scan result

### ISSUE THREAD

**Issue by odejinmi** [yushulx/flutter_barcode_sdk#42]
<img width="1440" alt="Screenshot 2023-08-18 at 7 19 33 AM" src="https://github.com/yushulx/flutter_barcode_sdk/assets/45696129/848e00fc-1e84-402d-aaf8-b88033068b13">

what causes the error

**Comment by yushulx** [comment]
@odejinmi do you have a valid [license key](https://www.dynamsoft.com/customer/license/trialLicense?product=dbr)?

**Comment by yushulx** [comment]
@odejinmi 
![image](https://github.com/yushulx/flutter_barcode_sdk/assets/2202306/e49f36a9-a3b1-4b51-a91d-28ea834e372e)

**Comment by odejinmi** [comment]
i just did that and still having error

**Comment by yushulx** [comment]
@odejinmi I just requested a new key `t0072oQAAAFT5/crUaYpTX2V3pAydsdjZhtDIoEtNp3xxsTa5F6LlU+NW3/RUjPPOUwrqjJLnCuKtYqSjaASv6pFVfMGdK9nRkyJP`. Try it out. 

![image](https://github.com/yushulx/flutter_barcode_sdk/assets/2202306/42415a31-6d6d-43cc-856a-f477c5505c29)

**Comment by yushulx** [comment]
@odejinmi if you still got the error:
1. Stop your app.
2. Remove cache files in `/Users/Shared/.Dynamsoft`.
3. Run your app with my license key.

**Comment by odejinmi** [comment]
thanks it has worked

**Comment by odejinmi** [comment]
will i need new gmail account to generate new trial license

**Comment by yushulx** [comment]
@odejinmi The SDK is not free. Generating trial licenses is not a sustainable long-term solution.
